def highlyDivisibleTriangularNumber(number):
    triangular_number = 0
    limit_reached = False
    toadd = 1
    divisors = 0
    prime_factors = []
    primes = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
        
    while(limit_reached == False):
        triangular_number += toadd
        prime_factors = getPrimeFactors(triangular_number, primes)
        divisors = getNumberOfDivisors(prime_factors)
        toadd += 1
        
        if(divisors >= 500):
            limit_reached = True
            for factor in prime_factors:
                print("%d^%d" % (factor[0],factor[1]))
            print("Number of Divisors = %d" % divisors)
    
    return triangular_number

def getPrimeFactors(number, primes):
    all_prime_factors = []
    j = 0
    power = 0
    
    temp_number = number
    while (j < len(primes)):
        if(temp_number == 1):
            all_prime_factors.append([primes[j],power])
            break
        if(temp_number % primes[j] == 0):
            temp_number = temp_number/primes[j]
            power = power + 1
        else:
            if (power != 0):
                all_prime_factors.append([primes[j],power])
            power = 0
            j = j+1
                
    return all_prime_factors

def getNumberOfDivisors(prime_factors):
    divisors = 1
    
    for factor in prime_factors:
        divisors *= factor[1]+1
        
    return divisors

def printProblemStatement():
    print("Problem 12:")
    print("Highly divisible triangular number")
    print("==================================")
    print("The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:")
    print("1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...")
    print("Let us list the factors of the first seven triangle numbers:")
    print("\t 1: 1\n\t 3: 1,3\n\t 6: 1,2,3,6\n\t10: 1,2,5,10\n\t15: 1,3,5,15\n\t21: 1,3,7,21\n\t28: 1,2,4,7,14,28");
    print("We can see that 28 is the first triangle number to have over five divisors.")
    print("What is the value of the first triangle number to have over five hundred divisors?\n")

def main():
    printProblemStatement()
    print("The solution:")
    print("=============")
    print("\nThe triangular number is: %d" % highlyDivisibleTriangularNumber(500))

main()